name = "Firefly"
uuid = "38d273ff-5bca-42e1-8e07-0e7ae0d15fdd"
authors = ["Miles Lucas <mdlucas@hawaii.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.3"
